name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          MARKETING_PRODUCTION_DOMAIN: https://marketing-mfe.netlify.app/

      - name: Deploy to Netlify
        run: npx netlify deploy --prod --dir=dist --site ${{ secrets.NETLIFY_CONTAINER_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
